### ISSUE TITLE
[idea] Demo hosting?

### ISSUE THREAD

**Issue by JulianNorton** [Kehom/gdMultiplayerTutorial#1]
Is there any example of the demo or reference I can check? It's hard for me to understand the final output.

**Comment by Kehom** [comment]
Hi, I'm truly sorry if I didn't understand your question correctly. Everything in this repository is the result of all the instructions in two written tutorials that can be found on my website. In there I (at least try) to explain the code. This repository is meant to be used as reference material, not exactly as the tutorials themselves.

My page can be found at http://kehomsforge.com
The first tutorial (which is an introduction) can be found at http://kehomsforge.com/tutorials/multi/gdMultiplayerSetup while the second, which is a followup can be found at http://kehomsforge.com/tutorials/multi/gdMoreNetworking

Again, sorry if that's not exactly what you wanted to know.

**Comment by JulianNorton** [comment]
Thanks for explaining. I was really impressed with the reference material and was hoping to find a example somewhere. I know this isn't related to your github, but I just want to find a working version of a hosted game using Godot. Most of my research has been projects that need to be compiled.

**Comment by Kehom** [comment]
Well, the code here is, in a way, the example shown in the tutorial. The main goal there is to show how to synchronize game objects with some relatively basic authoritative server structure (the followup tutorial). Based on your needs I'm afraid this repository may not be exactly what you are looking for.
Nevertheless, if you need any help with the code, just let me know.

**Comment by JulianNorton** [comment]
I appreciate it! Thanks again! Looking forward to your future articles.
