### ISSUE TITLE
Collisions doesn't work..

### ISSUE THREAD

**Issue by Arthurmtro** [Kehom/gdMultiplayerTutorial#4]
Sorry, i've follow your tutorial on your site but when i'm adding colliders for my games my character don't care of the collisionShape... it's been 3days and i'm starting to feel so bad :'(

**Comment by Kehom** [comment]
Hi,
There is little to no information to work with, making it very hard to help!
When you added colliders, your characters don't care about the collision shapes on the server? On the client? On both?
Can you make that work as desired without networking?

**Comment by Arthurmtro** [comment]
Hi!
Thank you for answering.
The problem is that I am developing a little multiplayer game following the tutorials you made, but when I add CollisionShape2D the character passes completely through and ignores the collision.
I don't understand, it comes from the code?

**Comment by Kehom** [comment]
Hello,
I really want to help but with little to no information it becomes almost impossible for anyone to do so!
Without knowing the behavior, much less what you did, the possibilities of what could be cause of the problem become rather huge!
Please, answer those:
- Is the described behavior happening on the server?
- Can you implement the desired behavior on a single player, separated project?
Please note that answering those questions still don't give enough information, but they can somewhat guide into a direction.

**Comment by Arthurmtro** [comment]
Hello, no problems.
Then the bug arrives in the server as well as solo on another project
I can send you my project code so you can see what's wrong.
I think the problem comes from the code directly!
Let's have a look if you want : https://github.com/Arthurmtro/gdtCounterStroke

**Comment by Kehom** [comment]
Ok, I did look into your project and the problem is in how the movement is being done. There is absolutely no collision detection with the system (Indeed, I didn't mention it in the tutorial). The easiest way is to use `move_and_slide()` or `move_and_collide()` functions, which will automatically check for collisions.

**Comment by Arthurmtro** [comment]
Oh... thanks !! i see what is the problem now :)
But now i absolutely dont know where i can put the move and slide function.
Because the movement is done into a Node2D script wich can't accept the move_and_slide function :o

**Comment by Kehom** [comment]
Convert the player character into a KinematicBody2D (make sure to also change the script from `extends Node2D` to `extends KinematicBody2D`). Once that is done you will be able to use those functions.

**Comment by Arthurmtro** [comment]
thank you very much now my character detects collisions but this bug enormously, I will try to correct all of it. thanks again for the help!
